name: Deploy Opik docs
run-name: Deploy docs ${{ github.ref_name }} to S3 ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select environment
        required: true
        default: staging
jobs:
  upload:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:      
      - name: checkout
        uses: actions/checkout@v4.1.1
